---
version: "3.3"
services:
    call-records:
        build:
            context: ./
            dockerfile: Dockerfile
        image: work-at-olist_img
        networks:
            - olist_net
        ports:
            - "80:80"
networks:
    olist_net:
        driver: bridge

- PORT: 80
